.net/Spliter/Models/ErrorViewModel.cs
namespace Spliter.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

.net/Spliter/Models/SpliterModel.cs
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.ComponentModel.DataAnnotations;
using System.Text.RegularExpressions;

namespace Spliter.Models;


public class spliter
{
    public spliter()
    {

    }
    public string? contenido { get; set; }
    public int Opcion { get; set; }     //propiedad que nos ayudara a distinguir la opcion que deseemos ejecutar.

    public string? cadenaBuscada { get; set; }

    public string? cadenaRemplazo { get; set; }
    public string? separador { get; set; }

    public string[]? contenidoSpliter { get; set; }

    #region explicacion de la propiedad Opcion
    /*
     *Esto nos ayudara a manejar mejor las opciones del usuario
     *
     *1->Limpiar caja de entrada
     *2->Eliminar espacios en blanco
     *3->Eliminar saltos de linea
     *4->Remplazar contenido.
     *
     */
    #endregion


    public void splitear()
    {
        try
        {
            if( this.separador == null )
            {
                separador = " ";
            }

            this.contenidoSpliter = this.contenido.Split(this.separador);

        }catch( Exception ex)
        {
            string[] arreglo = { "No se pudo realizar el analisis" };
            this.contenidoSpliter =  arreglo;
        }
    }

    public string eliminarBlanco()
    {
        if (this.contenido == null || this.contenido == string.Empty)
        {
            this.contenido = "sin contenido";
        }

        this.contenido = this.contenido.Replace("\r", "");

        return Regex.Replace(this.contenido, @" +", " ").Trim();
    }

    public string eliminarSalto()
    {
        Console.WriteLine($"desde la funcion");

        if (this.contenido == null || this.contenido == string.Empty)
        {
            this.contenido = "sin contenido";
        }

        this.contenido = this.contenido.Replace("\r", "");

        return Regex.Replace(this.contenido, @"[\n][\n]+", "\n\n").Trim();
    }


    //funcion para remplazar en base a una expresion regular.
    public string reemplzarString()
    {
        Console.WriteLine($"desde la funcion");

        if (this.contenido == null || this.contenido == string.Empty)
        {
            this.contenido = "sin contenido";
        }

        this.contenido = this.contenido.Replace("\r", "");

        string cad_1 = this.cadenaBuscada + "+";

        string resultado = "No se pudo realizar...";
        try
        {
            return Regex.Replace(this.contenido, cad_1, this.cadenaRemplazo).Trim();
        }
        catch (Exception a)
        {
            Console.WriteLine(a.Message);
            return resultado;
        }
    }

}

.net/Spliter/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Spliter.Models;
using System.Diagnostics;

namespace Spliter.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

.net/Spliter/Controllers/SpliterController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Spliter.Models;
namespace Spliter.Controllers;

public class SpliterController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public SpliterController()
    {

    }

    public IActionResult Index(spliter? cadena)
    {

        if (cadena != null)
        {

            return View( "Index",cadena );
        }
        spliter tmp = new spliter();
        tmp.contenido = "";
        ViewData["result"] = "Sin contenido...";
        return View( "Index", tmp );
    }


    [HttpPost]
    public IActionResult Evaluar(spliter obj)
    {
        try
        {
            if (obj == null)
            {
                return Index( null );
            }

            Console.WriteLine("L 32");
            //realizar la evaluacion
            switch (obj.Opcion)
            {
                case 1:
                    return Reset_box();
                case 2:
                    return eliminarBlanco(obj);

                case 3:
                    return eliminarSalto(obj);

                case 4:
                    return RemplazarContenido(obj);
                case 5:
                    return AplicarSplit( obj );
                default:
                    Console.WriteLine("Ocurrio un error...");
                    ViewData["result"] = "Seleccione una opcion valida...";
                    return Index( obj );

            }


        }
        catch (Exception ex)
        {

            Console.WriteLine("Ocurrio un error en el lado del controlador...");
            Console.WriteLine(ex.Message);
            return Index(null);
        }

    }


    [HttpPost]
    public IActionResult eliminarBlanco([Bind("contenido")] spliter spli)
    {

        if (ModelState.IsValid)
        {
            Console.WriteLine($"el modelo es valido elimB");

            ViewData["result"] = spli.eliminarBlanco();
            return Index(spli);
        }
        else
        {

            Console.WriteLine($"el modelo no es valido elimB");

            ViewData["result"] = "No se pudo realizar el analisis";
            spliter tmp = new spliter();
            return Index(tmp);
        }
    }

    [HttpPost]
    public IActionResult eliminarSalto([Bind("contenido")] spliter tmp)
    {
        if (ModelState.IsValid)
        {
            Console.WriteLine($"el modelo es valido elimS");

            ViewData["result"] = tmp.eliminarSalto();

            return Index(tmp);
        }
        else
        {

            Console.WriteLine($"el modelo no es valido elimS");

            ViewData["result"] = "No se pudo realizar el analisis";
            spliter tmp_tm = new spliter();
            return Index(tmp_tm);
        }
    }

    [HttpPost]
    public IActionResult Reset_box()
    {
        ViewData["contenido"] = " ";
        ViewData["result"] = " ";
        spliter tmp = new spliter();
        tmp.contenido = "";

        Console.WriteLine("DESDE RESET BOX");

        return Index(tmp);
    }

    public IActionResult RemplazarContenido([Bind("contenido,cadenaBuscada,cadenaRemplazo")] spliter tmp)
    {
        if (ModelState.IsValid)
        {
            Console.WriteLine($"el modelo es valido RemplazarContenido");

            ViewData["result"] = tmp.reemplzarString();

            return Index(tmp);
        }
        else
        {

            Console.WriteLine($"el modelo no es valido elimS");

            ViewData["result"] = "No se pudo realizar el analisis";
            spliter tmp_tm = new spliter();
            return Index(tmp_tm);
        }
    }

    public IActionResult AplicarSplit([Bind("contenido,separador")] spliter tmp)
    {
        if (ModelState.IsValid)
        {
            Console.WriteLine($"el modelo es valido aplicarSplit");

            //realizar el metodo splitear.
            tmp.splitear();

            ViewData["result"] = "Visualice la tabla que se encuentra debajo de este componente.";

            return Index(tmp);
        }
        else
        {

            Console.WriteLine($"el modelo no es valido aplicarSplit");

            ViewData["result"] = "No se pudo realizar el analisis";
            spliter tmp_tm = new spliter();
            return Index(tmp_tm);
        }
    }


    public IActionResult Privacy()
    {
        return View();
    }

    public IActionResult About()
    {
        return View();
    }

    public IActionResult Contact()
    {
        return View();
    }

    public IActionResult Instrucciones()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

.net/Spliter/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

.net/Spliter/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - spliter</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/spliter.styles.css" asp-append-version="true" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Spliter" asp-action="Index"><strong>Spliter</strong></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 justify-content-end">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Spliter" asp-action="Index">Comenzar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Spliter" asp-action="Instrucciones">Información </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Spliter" asp-action="About">Sobre el desarrollador</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Spliter" asp-action="Contact">Contacto del desarrollador</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container container_propio">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - spliter -
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

.net/Spliter/Views/Spliter/About.cshtml
@{
    ViewData["Title"] = "Sobre el desarrollador";
}
<div class="texto">
    <h1>@ViewData["Title"]</h1>
</div>

<hr>

<h2>Hola!</h2>
<br>

<p class="parrafo">
    Mi nombre es Tomás Morales, un apasionado por la tecnología y el desarrollo de software. Soy un programador autodidacta y me gusta aprender nuevas habilidades para mejorar mis capacidades. 
</p>

<p class="parrafo">
    Actualmente me encuentro estudiando <strong>ingeniería en ciencias y sistemas</strong> en la universidad de San Carlos de Guatemala, cursando el sexto semestre.
</p>

<p class="parrafo">
    Tengo experiencia en el manejo de lenguajes como <strong>Java, C#, Python</strong> y en tecnologías como <strong>Entity Framework, SQL server, LINQ y ASP.NET</strong> también poseo conocimiento en <strong>HTML y CSS</strong>. Me gusta utilizar los conocimientos adquiridos en mi formación académica para poder resolver problemas de manera eficiente. 
</p>

<p class="parrafo">
    Me gusta trabajar en equipo y considero que soy un buen compañero de equipo. Soy proactivo y siempre busco nuevas formas de mejorar mis habilidades y aportar a los proyectos en los que trabajo.
    Estoy entusiasmado por aprender más sobre diferentes tecnologías y aplicarlas en proyectos reales. Mi objetivo es convertirme en un desarrollador de software experto y aplicar los conocimientos que he adquirido en mi carrera universitaria.
</p>

<hr>

.net/Spliter/Views/Spliter/Contact.cshtml
@{
    ViewData["Title"] = "Contacto del desarrollador";
}
<div class="texto">
    <h1>@ViewData["Title"]</h1>
</div>

<hr>

<h2>Hola!</h2>
<br>

<p class="parrafo">
    Mi nombre es Tomás Morales, un apasionado por la tecnología y el desarrollo de software.
</p>

<p class="parrafo">
    Actualmente me encuentro estudiando <strong>ingeniería en ciencias y sistemas</strong> en la universidad de San Carlos de Guatemala, cursando el sexto semestre.
</p>

<p>
    Te dejo mi contacto para que podamos conversar 🥸
</p>

<ul>
    <li><a href="https://www.linkedin.com/in/tomas-morales-s/" target="_blank"><strong>LinkedIn</strong></a></li>
    <br>
    <li><a href="https://github.com/AlejoMora991014" target="_blank"><strong>GitHub</strong></a></li>
</ul>

<hr>

.net/Spliter/Views/Spliter/Index.cshtml
@model spliter;

@{
    ViewData["Title"] = "Spliter";
}


<form method="POST">
    <div class="contenedorPadre">

        <div class="contenedor1">
            <div>
                <div class="form-floating">
                    <textarea asp-for="contenido" class="form-control" placeholder="Coloca acá tu texto" id="floatingTextarea">@Model.contenido</textarea>
                    <label asp-for="contenido" for="floatingTextarea">Coloca tu texto acá</label>
                    <span asp-validation-for="contenido" class="text-danger"></span>
                </div>
            </div>
        </div>

        <div class="contenedor1">
            <div class="input-group flex-nowrap">
                <span class="input-group-text" id="addon-wrapping">Seperador</span>
                <input type="text" pattern="[\w|\W]+" asp-for="separador" class="form-control" placeholder="elemento separador" aria-label="elemento separador">
            </div>
        </div>

        <div class="contenedor1">
            <div class="input-group flex-nowrap">
                <span class="input-group-text" id="addon-wrapping">Texto buscado</span>
                <input type="text" asp-for="cadenaBuscada" class="form-control" placeholder="cadena buscada" aria-label="Cadena buscada">
            </div>
        </div>

        <div class="contenedor1">
            <div class="input-group flex-nowrap">
                <span class="input-group-text" id="addon-wrapping">Texto remplazo</span>
                <input type="text" asp-for="cadenaRemplazo" class="form-control" placeholder="cadena remplazo" aria-label="Cadena remplazo">
            </div>
        </div>


        <div class="contenedor2">

            <select class="form-select " aria-label="Default select example" asp-for="Opcion">
                <option selected>Selecciona una opcion</option>

                <option value="1">Limpiar caja de entrada</option>
                <option value="2">Eliminar espacios en blanco</option>
                <option value="3">Eliminar saltos de linea</option>
                <option value="4">Remplazar contenido.</option>
                <option value="5">Aplicar separador en el texto.</option>

            </select>

            <br />

            <button type="submit" asp-action="Evaluar" class="btn btn-success">Ejecutar</button>

        </div>
    </div>
</form>


<div>
    <div class="contenedor3">
        <div>
            <div class="form-floating">
                <textarea class="form-control" placeholder="Resultado" id="floatingTextarea">@ViewData["result"]</textarea>
                <label for="floatingTextarea">Resultado</label>
            </div>
        </div>
    </div>
</div>


@if (Model.contenidoSpliter != null)
{
    <div class="contenedor1">
        <table class="table table-secondary table-hover" id="tablaResultante">
            <thead>
                <tr>
                    <th scope="col"># elemento</th>
                    <th scope="col">Contenido</th>
                </tr>
            </thead>
            <tbody>


                @for (int i = 0; i < Model.contenidoSpliter.Length; i++)
                {
                    if (@Model.contenidoSpliter[i] != "")
                    {
                        int contador = i + 1;
                        <tr>
                            <th scope="row"> @contador </th>
                            <td> @Model.contenidoSpliter[ i ] </td>
                        </tr>
                    }
                }

            </tbody>
        </table>

        <br />
        <button type="button" class="btn btn-success" onclick="descargarTabla()">Descargar tabla (xlsx)</button>
        <br />
        

    </div>
}


@*Script para poder actualizar el area de contenido*@
<script>
    // Obtener el elemento del textarea
    var textarea = document.getElementById("floatingTextarea");

    // Función para actualizar el valor del textarea
    function updateTextArea() {

        var contenido = "@Model.contenido";

        textarea.value = contenido;
        console.log(@Model.contenido );
    }

    // Llamar la función al cargar la página
    updateTextArea();
</script>

@*Script para descargar la tabla en formato xlsx*@

<!-- Agrega la siguiente biblioteca SheetJS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.16.8/xlsx.full.min.js"></script>

<script>
    function descargarTabla() {
        const nombreArchivo = "tablaResultante.xlsx";
        const tabla = document.getElementById("tablaResultante");
        const libro = XLSX.utils.table_to_book(tabla, { sheet: "Sheet1" });
        XLSX.writeFile(libro, nombreArchivo);
    }
</script>


@*Script para descargar la tabla en formato pdf*@

.net/Spliter/Views/Spliter/Instrucciones.cshtml
@{
    ViewData["Title"] = "Instrucciones de uso";
}
<div class="texto">
    <h1>@ViewData["Title"]</h1>
</div>

<hr>

<h2>Hola!</h2>
<h5>Acá te dejo algunas aclaraciones e instrucciones para que puedas utilizar la aplicación, espero te sea de utilidad.</h5>
<br>

<hr />

<h1>¿Qué es?</h1>
<p class="parrafo">
    Spliter es una herramienta que te ayuda a poder manipular contenido de texto, es decir que puedes realizar diferentes modificaciones a un texto que ingresas en la caja de contenido 😀
</p>

<br/>
<br/>

<hr>

<h1>¿Qué puede hacer la aplicación?</h1>

<p class="parrafo">
Al utilizar Spliter puedes realizar modificaciones de texto rápidas sin necesidad de descargar aplicaciones en tu dispositivo.
</p>

<br />

<h3>Eliminar espacios en blanco</h3>

<p class="parrafo" >
    Podrás eliminar espacios en blanco entre el texto, es decir que si nuestro texto original posee espacios en blanco extras podremos eliminarlos para que nos quede más legible.
</p>

<br/>

<figure>
    <img src="https://i.imgur.com/5wMTR13.jpg" alt="Imagen que muestra el area de texto inicial.">
    <figcaption style="font-style: italic;">Texto inicial</figcaption>
</figure>

<br/>

<figure>
    <img src="https://i.imgur.com/IZD5Cgy.jpg" alt="Imagen que muestra la seleccion para eliminar espacios en blanco.">
    <figcaption style="font-style: italic;">Seleccionamos la opción de “Eliminar espacios en blanco”</figcaption>
</figure>

<br />

<figure>
    <img src="https://i.imgur.com/wQD82gQ.jpg" alt="Imagen que muestra el boton de ejecutar.">
    <figcaption style="font-style: italic;">Presionamos el botón de ejecutar para comenzar el proceso.</figcaption>
</figure>

<br />

<figure>
    <img src="https://i.imgur.com/QuChExO.jpg" alt="Imagen que muestra resultado de la ejecucion">
    <figcaption style="font-style: italic;">Texto resultante.</figcaption>
</figure>

<br />

<hr>

@*Apartado de saltos de linea*@

<h3>Eliminar saltos de linea extra</h3>

<p class="parrafo">
    Utilizando la opción “Eliminar saltos de línea” podrás estandarizar todo el texto a solo un salto de línea.
</p>

<br />


<figure>
    <img src="https://i.imgur.com/KOULkzd.jpg" alt="Imagen que muestra el texto ingresado">
    <figcaption style="font-style: italic;">Texto ingresado.</figcaption>
</figure>

<br />


<figure>
    <img src="https://i.imgur.com/2nNDXCg.jpg" alt="Imagen que muestra la opcion seleccionada">
    <figcaption style="font-style: italic;">Seleccionamos la opción “Eliminar saltos de línea” y presionamos el boton "ejecutar"</figcaption>
</figure>

<br />

<figure>
    <img src="https://i.imgur.com/clAgIZm.jpg" alt="Imagen que muestra el texto resultante">
    <figcaption style="font-style: italic;">Imagen que muestra el texto resultante.</figcaption>
</figure>

<br />

<hr />

@*Apartado de remplazar cadenas*@

<h3>Remplazar texto</h3>

<p class="parrafo">
    Podrás realizar un remplazo de palabras ya sea por palabras especificas o por “Expresiones Regulares" 
    (tomar en cuenta que a cada expresión se le agrega un carácter ‘+’ al final).
</p>

<br />


<figure>
    <img src="https://i.imgur.com/vvqe9Lc.jpg" alt="Imagen que muestra el texto ingresado">
    <figcaption style="font-style: italic;">Texto ingresado.</figcaption>
</figure>

<br />


<figure>
    <img src="https://i.imgur.com/NuMPTT5.jpg" alt="Imagen que muestra las casillas que debemos llenar.">
    <figcaption style="font-style: italic;">Indicamos el texto buscado y el texto que tomara su lugar.</figcaption>
</figure>

<br />

<figure>
    <img src="https://i.imgur.com/gcWIAAx.jpg" alt="Imagen que muestra la seleccion de la opcion y el boton de ejecutar.">
    <figcaption style="font-style: italic;">Seleccionamos la opción “Remplazar contenido” y lo ejecutamos</figcaption>
</figure>

<br />

<figure>
    <img src="https://i.imgur.com/Fu0P9SK.jpg" alt="Imagen que muestra el resultado de la ejecucion.">
    <figcaption style="font-style: italic;">Texto resultante</figcaption>
</figure>

<br />

<hr />

@*Apartado de split*@

<h3>Aplicar un separador a nuestro texto</h3>

<p class="parrafo">
    Podrás aplicar un separador en todo el texto, esto aplicará la función “Split”, el separador lo que hará es tomar el 
    texto y dividir el contenido de nuestro texto mediante el texto/carácter que le mandemos. El resultado se visualizará 
    en una tabla HTML, dicha tabla la podremos descargar en formato “XLSX” ( futuramente en otros formatos).
</p>

<br />

<p class="parrafo">
    Se aconseja utilizar esta función para poder visualizar de manera más legible textos que vengan en formato CSV,
    por ejemplo, si tiene un listado de números de la siguiente manera : “1,2,3,4,5,6,7,8,9,10…” podrá poner el carácter de
    “coma” como separador para que los números se le sean presentados en una tabla y pueda manipularlos como prefiera.
</p>

<br />

<figure>
    <img src="https://i.imgur.com/pssql5F.jpg" alt="Imagen que muestra el texto ingresado">
    <figcaption style="font-style: italic;">Texto ingresado.</figcaption>
</figure>

<br />

<figure>
    <img src="https://i.imgur.com/pZvugvy.jpg" alt="Imagen que muestra el separador ingresado">
    <figcaption style="font-style: italic;">Nuestro separador indicara un punto de corte en el texto, cabe aclarar 
        que este separador no se tomara en cuenta en la cadena.</figcaption>
</figure>

<br />

<figure>
    <img src="https://i.imgur.com/fvqHJ4A.jpg" alt="Imagen que muestra la seleccion y el boton de ejecucion.">
    <figcaption style="font-style: italic;">Seleccionamos la opción “Aplicar separador en el texto” y ejecutamos.</figcaption>
</figure>

<br />


<figure>
    <img src="https://i.imgur.com/JbEtvPq.jpg" alt="Imagen que muestra un mensaje de resultado.">
    <figcaption style="font-style: italic;">Mensaje en la caja de resultados.</figcaption>
</figure>

<br />

<figure>
    <img src="https://i.imgur.com/c0yZBcf.jpg" alt="Imagen que muestra la tabla resultante.">
    <figcaption style="font-style: italic;">Imagen que muestra la tabla resultante y el boton que permite la descarga de
         la tabla en los formatos disponibles.</figcaption>
</figure>

<br />


<hr />

<h2>NOTA :::::::::</h2>
<p class="parrafo" style="font-style: italic;">

    Este proyecto es de uso público y sin fines de lucro. Si he infringido alguna normativa relacionada
    con derechos de autor o la utilización de librerías, estoy abiertos a dialogar y llegar a un acuerdo.
    Buscando asegurarme de que el proyecto sea ético y legal. Agradezco tu comprensión y colaboración. ¡Muchas gracias!
</p>

.net/Spliter/Views/Spliter/Reset_box.cshtml
@{
    ViewData["Title"] = "Reset?";
}
<div class="texto">
    <h1>@ViewData["Title"]</h1>
</div>

<hr>

<h2>Hola!</h2>
<br>

<p class="parrafo">
    No deberias poder ver esto
</p>

.net/Spliter/Views/Spliter/eliminarBlanco.cshtml
@{
    ViewData["Title"] = "eliminar?";
}
<div class="texto">
    <h1>@ViewData["Title"]</h1>
</div>

<hr>

<h2>Hola!</h2>
<br>

<p class="parrafo">
    No deberias poder ver esto
</p>

.net/Spliter/Views/Spliter/eliminarSalto.cshtml
@{
    ViewData["Title"] = "salto?";
}
<div class="texto">
    <h1>@ViewData["Title"]</h1>
</div>

<hr>

<h2>Hola!</h2>
<br>

<p class="parrafo">
    No deberias poder ver esto salto
</p>

.net/Spliter/Views/Spliter/indexCpy.cshtml
@{
    ViewData["Title"] = "Spliter";
}

<div class="contenedorPadre">


    <div class="contenedor1">
        <div>
            <div class="form-floating">
                <textarea class="form-control" placeholder="Coloca acá tu texto" id="floatingTextarea">@ViewData["cadena"]</textarea>
                <label for="floatingTextarea">Coloca tu texto acá</label>
            </div>
        </div>
    </div>

    @* form para envio de data *@
    <form asp-action="POST">
        <div class="dropdown contenedor2">
        <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            Seleccione una opcion
        </button>
        <ul class="dropdown-menu">
            <li><button class="dropdown-item" type="submit" asp-action="index">Eliminar espacios en blanco extra.</button></li>
            <li><button class="dropdown-item" type="submit">Eliminar saltos de linea extra</button></li>
            <li><button class="dropdown-item" type="submit">Limpiar caja de texto</button></li>
        </ul>
    </div>
    </form>
    @* fin form *@

</div>

<div>
    <div class="contenedor3">
        <div>
            <div class="form-floating">
                <textarea class="form-control" placeholder="Resultado" id="floatingTextarea">@ViewData["Resultado"]</textarea>
                <label for="floatingTextarea">Resultado</label>
            </div>
        </div>
    </div>

</div>